In [61]:
import pandas as pd

In [90]:
kospi = pd.read_csv('csv/코스피.csv')
kosdaq = pd.read_csv('csv/코스닥.csv')
list = pd.read_csv('csv/기업목록.csv', index_col=0)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_63299/1287368341.py:1: DtypeWarning: Columns (5,7,18,123,140) have mixed types. Specify dtype option on import or set low_memory=False.
  kospi = pd.read_csv('csv/코스피.csv')
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_63299/1287368341.py:2: DtypeWarning: Columns (5,7,17,18,123,139,140,142,167) have mixed types. Specify dtype option on import or set low_memory=False.
  kosdaq = pd.read_csv('csv/코스닥.csv')

In [92]:
list = list[~list['Symbol'].isin(['A000570',
'A002950',
'A000830',
'A104110',
'A057110',
'A021570',
'A131390',
'A002300',
'A032380',
'A012830'])]
list

        Name   회계년   레이블   Symbol
0      AD모터스  2011  부실징후  A038120
1      AD모터스  2012  부실징후  A038120
2        AJS  2013  부실징후  A013340
3        AJS  2014  부실징후  A013340
4        APS  2016  부실징후  A054620
...      ...   ...   ...      ...
10716     힘스  2018  부실징후  A238490
10717     힘스  2019    회복  A238490
10718     힘스  2021  부실징후  A238490
10719     힘스  2022  부실징후  A238490
10720     힘스  2023  부실징후  A238490

[10715 rows x 4 columns]

In [93]:
kospi['시장'] = 'KOSPI'
kosdaq['시장'] = 'KOSDAQ'

In [94]:
kosdaq

,Symbol,Name,결산월,회계년,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),현금및현금성자산구성비율(%),유형자산구성비율(%),...,자본금지배주주순이익률(%),총자산회전율(회),총자산회전율(3년평균)(회),총부채회전율(회),총자본회전율(회),자본금회전율(회),부가가치(천원),자본생산성(%),노동생산성(천원),시장
0,A247540,에코프로비엠,12,2010,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
1,A247540,에코프로비엠,12,2011,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
2,A247540,에코프로비엠,12,2012,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
3,A247540,에코프로비엠,12,2013,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
4,A247540,에코프로비엠,12,2014,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32643,A900180,완리,12,2019,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
32644,A900180,완리,12,2020,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
32645,A900180,완리,12,2021,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
32646,A900180,완리,12,2022,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ
32647,A900180,완리,12,2023,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOSDAQ

In [95]:
data = pd.concat([kospi, kosdaq])
data.reset_index(drop=True, inplace=True)

In [96]:
data = pd.merge(list, data, on=['Symbol', '회계년'], how='left')
data

,Name_x,회계년,레이블,Symbol,Name_y,결산월,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),...,자본금지배주주순이익률(%),총자산회전율(회),총자산회전율(3년평균)(회),총부채회전율(회),총자본회전율(회),자본금회전율(회),부가가치(천원),자본생산성(%),노동생산성(천원),시장
0,AD모터스,2011,부실징후,A038120,AD모터스,12,Annual,19.35,80.65,2.34,...,N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),NaN,NaN,NaN,KOSDAQ
1,AD모터스,2012,부실징후,A038120,AD모터스,12,Annual,37.53,62.47,13.76,...,-131.66,0.06,N/A(IFRS),0.26,0.09,0.11,NaN,NaN,NaN,KOSDAQ
2,AJS,2013,부실징후,A013340,AJS,12,Annual,99.85,0.15,69.15,...,-218.04,0.50,0.57,0.76,1.49,1.56,NaN,NaN,NaN,KOSDAQ
3,AJS,2014,부실징후,A013340,AJS,12,Annual,104.02,완전잠식,0.88,...,-95.45,0.23,0.46,0.23,완전잠식,0.61,NaN,NaN,NaN,KOSDAQ
4,APS,2016,부실징후,A054620,APS,12,Annual,60.49,39.51,19.72,...,214.83,0.00,0.51,0.00,0.00,0.01,NaN,NaN,NaN,KOSDAQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10710,힘스,2018,부실징후,A238490,힘스,12,Annual,19.37,80.63,6.14,...,-37.45,0.52,1.12,2.16,0.68,12.99,NaN,NaN,NaN,KOSDAQ
10711,힘스,2019,회복,A238490,힘스,12,Annual,29.93,70.07,5.16,...,298.52,1.12,1.04,4.41,1.50,30.08,NaN,NaN,NaN,KOSDAQ
10712,힘스,2021,부실징후,A238490,힘스,12,Annual,12.31,87.69,0.56,...,-7.80,0.58,0.99,4.31,0.67,8.94,NaN,NaN,NaN,KOSDAQ
10713,힘스,2022,부실징후,A238490,힘스,12,Annual,22.11,77.89,8.86,...,-152.85,0.39,0.74,2.26,0.46,5.58,NaN,NaN,NaN,KOSDAQ
10714,힘스,2023,부실징후,A238490,힘스,12,Annual,28.31,71.69,6.39,...,99.00,0.57,0.50,2.24,0.77,8.86,NaN,NaN,NaN,KOSDAQ

In [86]:
duplicated_rows = data[data.duplicated(subset=['Name', '회계년'], keep=False)]
print(duplicated_rows)

        Name   회계년   레이블 Symbol_x Symbol_y  결산월      주기 타인자본비율(%) 자기자본비율(%)  \
1087   고려시멘트  2019  부실징후  A198440  A003660   12  Annual       NaN       NaN
1088   고려시멘트  2019  부실징후  A198440  A198440   12  Annual     30.38     69.62
1089   고려시멘트  2020    회복  A198440  A003660   12  Annual       NaN       NaN
1090   고려시멘트  2020    회복  A198440  A198440   12  Annual     19.92     80.08
1091   고려시멘트  2022  부실징후  A198440  A003660   12  Annual       NaN       NaN
...      ...   ...   ...      ...      ...  ...     ...       ...       ...
10503  핸디소프트  2020    회복  A220180  A032380   12  Annual       NaN       NaN
10540  현대리바트  2022  부실징후  A079430  A079430   12  Annual     48.59     51.41
10541  현대리바트  2022  부실징후  A079430  A012830   12  Annual       NaN       NaN
10542  현대리바트  2023  부실징후  A079430  A079430   12  Annual     55.14     44.86
10543  현대리바트  2023  부실징후  A079430  A012830   12  Annual       NaN       NaN

      차입금의존도(%)  ...  자본금지배주주순이익률(%)  총자산회전율(회)  총자산회전율(3년평균)(회) 총부채회전율(회)  \
1087        NaN  ...             NaN        NaN              NaN       NaN
1088        9.5  ...          106.21       0.56             0.66      1.78
1089        NaN  ...             NaN        NaN              NaN       NaN
1090       1.21  ...          139.00       0.58             0.58      2.28
1091        NaN  ...             NaN        NaN              NaN       NaN
...         ...  ...             ...        ...              ...       ...
10503       NaN  ...             NaN        NaN              NaN       NaN
10540     18.39  ...         -241.23       1.72             1.73      3.75
10541       NaN  ...             NaN        NaN              NaN       NaN
10542     19.89  ...         -169.05       1.78             1.73      3.43
10543       NaN  ...             NaN        NaN              NaN       NaN

      총자본회전율(회) 자본금회전율(회) 부가가치(천원) 자본생산성(%) 노동생산성(천원)      시장
1087        NaN       NaN      NaN      NaN       NaN   KOSPI
1088       0.81     22.18      NaN      NaN       NaN  KOSDAQ
1089        NaN       NaN      NaN      NaN       NaN   KOSPI
1090       0.78     21.95      NaN      NaN       NaN  KOSDAQ
1091        NaN       NaN      NaN      NaN       NaN   KOSPI
...         ...       ...      ...      ...       ...     ...
10503       NaN       NaN      NaN      NaN       NaN  KOSDAQ
10540      3.17     71.25      NaN      NaN       NaN   KOSPI
10541       NaN       NaN      NaN      NaN       NaN   KOSPI
10542      3.71     75.58      NaN      NaN       NaN   KOSPI
10543       NaN       NaN      NaN      NaN       NaN   KOSPI

[132 rows x 172 columns]

In [87]:
duplicated_rows.to_csv('중복데이터.csv', encoding='utf-8-sig')

In [88]:
duplicated_rows['Name'].nunique()

11

In [73]:
data2 = data[['Name','Symbol','회계년']]
data2

        Name   Symbol   회계년
0      AD모터스  A038120  2011
1      AD모터스  A038120  2012
2        AJS  A013340  2013
3        AJS  A013340  2014
4        APS  A054620  2016
...      ...      ...   ...
10782     힘스  A238490  2018
10783     힘스  A238490  2019
10784     힘스  A238490  2021
10785     힘스  A238490  2022
10786     힘스  A238490  2023

[10725 rows x 3 columns]

In [76]:
a = pd.merge(list, data2, on=['Name','회계년'], how='left')
a

        Name   회계년   레이블   Symbol
0      AD모터스  2011  부실징후  A038120
1      AD모터스  2012  부실징후  A038120
2        AJS  2013  부실징후  A013340
3        AJS  2014  부실징후  A013340
4        APS  2016  부실징후  A054620
...      ...   ...   ...      ...
10726     힘스  2018  부실징후  A238490
10727     힘스  2019    회복  A238490
10728     힘스  2021  부실징후  A238490
10729     힘스  2022  부실징후  A238490
10730     힘스  2023  부실징후  A238490

[10731 rows x 4 columns]

In [77]:
a[a['Name'] == '신성이엔지']

       Name   회계년   레이블   Symbol
4552  신성이엔지  2011  부실징후  A011930
4553  신성이엔지  2011  부실징후  A011930
4554  신성이엔지  2012  부실징후  A011930
4555  신성이엔지  2013  부실징후  A011930
4556  신성이엔지  2014  부실징후  A011930
4557  신성이엔지  2015  부실징후  A011930
4558  신성이엔지  2016  부실징후  A011930
4559  신성이엔지  2017  부실징후  A011930
4560  신성이엔지  2018  부실징후  A011930
4561  신성이엔지  2019  부실징후  A011930
4562  신성이엔지  2020  부실징후  A011930
4563  신성이엔지  2021  부실징후  A011930
4564  신성이엔지  2022  부실징후  A011930
4565  신성이엔지  2023  부실징후  A011930
4566  신성이엔지  2011    회복  A011930
4567  신성이엔지  2011    회복  A011930

In [97]:
data.to_csv('dataset.csv', encoding='utf-8-sig')

In [98]:
data.describe()

,회계년,결산월,현금및현금성자산구성비율(%),유형자산구성비율(%),무형자산구성비율(%),유보액/총자산(%),영업수익증가율(전분기)(%),매출액증가율(전분기)(%),"매출액증가율(직전4분기,전년동기)(%)","매출액증가율(직전4분기,전분기)(%)",...,EBITDAPS증가율(전분기)(%),"DPS증가율(보통주,전분기)(%)","DPS증가율(보통주,현금,전분기)(%)","DPS증가율(무상조정전,보통주,현금,전분기)(%)",영업이익률(직전4분기)(%),EBITDA마진율(직전4분기)(%),당기순이익률(직전4분기)(%),"ROA(영업이익,직전4분기)(%)","ROE(영업이익,직전4분기)(%)","ROE(당기순이익,직전4분기)(%)"
count,10715.000000,10715.000000,10715.000000,10715.000000,10715.000000,9347.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2017.742324,11.936724,10.371882,24.476564,3.557306,45.577838,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.591903,0.704733,13.141140,20.156046,7.621813,24.326887,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2011.000000,3.000000,0.000000,0.000000,0.000000,0.010000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2015.000000,12.000000,2.135000,6.550000,0.310000,26.560000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.000000,12.000000,5.770000,20.780000,1.000000,44.570000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2021.000000,12.000000,13.260000,38.180000,3.145000,63.695000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2023.000000,12.000000,96.470000,96.890000,91.850000,127.060000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
columns_to_drop = [col for col in data.columns if '분기' in col or '3년' in col or '5년' in col]
# columns_to_drop = [col for col in data.columns if '5년' in col]
df_filtered = data.drop(columns=columns_to_drop)
df_filtered

,Name_x,회계년,레이블,Symbol,Name_y,결산월,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),...,자본금세전계속사업이익률(%),자본금지배주주순이익률(%),총자산회전율(회),총부채회전율(회),총자본회전율(회),자본금회전율(회),부가가치(천원),자본생산성(%),노동생산성(천원),시장
0,AD모터스,2011,부실징후,A038120,AD모터스,12,Annual,19.35,80.65,2.34,...,N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),NaN,NaN,NaN,KOSDAQ
1,AD모터스,2012,부실징후,A038120,AD모터스,12,Annual,37.53,62.47,13.76,...,-131.66,-131.66,0.06,0.26,0.09,0.11,NaN,NaN,NaN,KOSDAQ
2,AJS,2013,부실징후,A013340,AJS,12,Annual,99.85,0.15,69.15,...,-210.63,-218.04,0.50,0.76,1.49,1.56,NaN,NaN,NaN,KOSDAQ
3,AJS,2014,부실징후,A013340,AJS,12,Annual,104.02,완전잠식,0.88,...,-95.45,-95.45,0.23,0.23,완전잠식,0.61,NaN,NaN,NaN,KOSDAQ
4,APS,2016,부실징후,A054620,APS,12,Annual,60.49,39.51,19.72,...,-20.69,214.83,0.00,0.00,0.00,0.01,NaN,NaN,NaN,KOSDAQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10710,힘스,2018,부실징후,A238490,힘스,12,Annual,19.37,80.63,6.14,...,-63.92,-37.45,0.52,2.16,0.68,12.99,NaN,NaN,NaN,KOSDAQ
10711,힘스,2019,회복,A238490,힘스,12,Annual,29.93,70.07,5.16,...,280.70,298.52,1.12,4.41,1.50,30.08,NaN,NaN,NaN,KOSDAQ
10712,힘스,2021,부실징후,A238490,힘스,12,Annual,12.31,87.69,0.56,...,-26.23,-7.80,0.58,4.31,0.67,8.94,NaN,NaN,NaN,KOSDAQ
10713,힘스,2022,부실징후,A238490,힘스,12,Annual,22.11,77.89,8.86,...,-199.98,-152.85,0.39,2.26,0.46,5.58,NaN,NaN,NaN,KOSDAQ
10714,힘스,2023,부실징후,A238490,힘스,12,Annual,28.31,71.69,6.39,...,107.03,99.00,0.57,2.24,0.77,8.86,NaN,NaN,NaN,KOSDAQ

In [107]:
columns_to_drop

['유보율(3년평균)(%)',
 '영업수익증가율(전분기)(%)',
 '매출액증가율(전분기)(%)',
 '매출액증가율(3년평균)(%)',
 '매출액증가율(5년평균)(%)',
 '매출액증가율(직전4분기,전년동기)(%)',
 '매출액증가율(직전4분기,전분기)(%)',
 '매출원가증가율(전분기)(%)',
 '매출총이익증가율(전분기)(%)',
 '판매비와관리비증가율(전분기)(%)',
 '영업이익증가율(전분기)(%)',
 '영업이익증가율(3년평균)(%)',
 '영업이익증가율(5년평균)(%)',
 '영업이익증가율(직전4분기,전년동기)(%)',
 '영업이익증가율(직전4분기,전분기)(%)',
 '*조정영업이익증가율(전분기)(%)',
 '세전계속사업이익증가율(전분기)(%)',
 '세전계속사업이익증가율(3년평균)(%)',
 '세전계속사업이익증가율(5년평균)(%)',
 '세전계속사업이익증가율(직전4분기,전년동기)(%)',
 '세전계속사업이익증가율(직전4분기,전분기)(%)',
 '계속사업이익증가율(전분기)(%)',
 '계속사업이익증가율(직전4분기,전년동기)(%)',
 '계속사업이익증가율(직전4분기,전분기)(%)',
 '중단사업이익증가율(전분기)(%)',
 '중단사업이익증가율(직전4분기,전년동기)(%)',
 '중단사업이익증가율(직전4분기,전분기)(%)',
 '당기순이익증가율(전분기)(%)',
 '당기순이익증가율(3년평균)(%)',
 '당기순이익증가율(5년평균)(%)',
 '당기순이익증가율(직전4분기,전년동기)(%)',
 '당기순이익증가율(직전4분기,전분기)(%)',
 '총포괄이익증가율(전분기)(%)',
 'EBITDA증가율(전분기)(%)',
 'EBITDA증가율(3년평균)(%)',
 'EBITDA증가율(5년평균)(%)',
 'EBITDA증가율(직전4분기,전년동기)(%)',
 'EBITDA증가율(직전4분기,전분기)(%)',
 '총자산증가율(전분기)(%)',
 '총자산증가율(3년평균)(%)',
 '총부채증가율(전분기)(%)',
 '총부채증가율(3년평균)(%)',
 '총자본증가율(전분기)(%)',
 '총자본증가율(3년평균)(%)',
 '자본금증가율(전분기)(%)',
 '자본금증가율(3년평균)(%)',
 'EPS증가율(전분기)(%)',
 'EPS증가율(3년평균)(%)',
 'EPS증가율(5년평균)(%)',
 'EPS(계속사업)증가율(전분기)(%)',
 'EPS증가율(보통주,전분기)(%)',
 'BPS증가율(전분기)(%)',
 'BPS증가율(무형자산차감,전분기)(%)',
 'CFPS증가율(전분기)(%)',
 'CFPS증가율(보통주,전분기)(%)',
 'SPS증가율(전분기)(%)',
 'EBITDAPS증가율(전분기)(%)',
 'EBITDAPS증가율(3년평균)(%)',
 'EBITDAPS증가율(5년평균)(%)',
 'DPS증가율(보통주,전분기)(%)',
 'DPS증가율(보통주,현금,전분기)(%)',
 'DPS증가율(보통주,현금,3년평균)(%)',
 'DPS증가율(무상조정전,보통주,현금,전분기)(%)',
 '영업이익률(3년평균)(%)',
 '영업이익률(직전4분기)(%)',
 'EBITDA마진율(3년평균)(%)',
 'EBITDA마진율(직전4분기)(%)',
 '세전계속사업이익률(3년평균)(%)',
 '당기순이익률(3년평균)(%)',
 '당기순이익률(직전4분기)(%)',
 'ROA(영업이익,3년평균)(%)',
 'ROA(영업이익,직전4분기)(%)',
 'ROA(당기순이익,3년평균)(%)',
 'ROE(영업이익,3년평균)(%)',
 'ROE(영업이익,직전4분기)(%)',
 'ROE(당기순이익,3년평균)(%)',
 'ROE(당기순이익,직전4분기)(%)',
 '총자산회전율(3년평균)(회)']

In [108]:
df_filtered.describe()

,회계년,결산월,현금및현금성자산구성비율(%),유형자산구성비율(%),무형자산구성비율(%),유보액/총자산(%)
count,10715.000000,10715.000000,10715.000000,10715.000000,10715.000000,9347.000000
mean,2017.742324,11.936724,10.371882,24.476564,3.557306,45.577838
std,3.591903,0.704733,13.141140,20.156046,7.621813,24.326887
min,2011.000000,3.000000,0.000000,0.000000,0.000000,0.010000
25%,2015.000000,12.000000,2.135000,6.550000,0.310000,26.560000
50%,2018.000000,12.000000,5.770000,20.780000,1.000000,44.570000
75%,2021.000000,12.000000,13.260000,38.180000,3.145000,63.695000
max,2023.000000,12.000000,96.470000,96.890000,91.850000,127.060000

In [109]:
df_filtered.to_csv('csv/dataset_컬럼제거(분기,3,5년).csv',encoding='utf-8-sig')