In [4]:
import pandas as pd
feature = pd.read_csv('csv/코스피코스닥연결재무비율.csv', index_col=0)
feature.reset_index(inplace=True)
label = pd.read_csv('csv/최종_label.csv', index_col=0)
label.reset_index(drop=True, inplace=True)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_71213/898085711.py:2: DtypeWarning: Columns (5,7,15,17,18,134,155,157,185) have mixed types. Specify dtype option on import or set low_memory=False.
  feature = pd.read_csv('csv/코스피코스닥연결재무비율.csv', index_col=0)

In [19]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)

In [7]:
label

       Symbol      Name   회계년  label_shifted
0     A038120     AD모터스  2011            0.0
1     A071660      SSCP  2011            0.0
2     A105070      금강제강  2011            0.0
3     A004550    대우송도개발  2011            0.0
4     A045260    디에이치패션  2011            0.0
...       ...       ...   ...            ...
7023  A900050    중국원양자원  2014            0.0
7024  A900050    중국원양자원  2015            0.0
7025  A900040   차이나그레이트  2017            0.0
7026  A950010  평산차업 KDR  2012            0.0
7027  A950010  평산차업 KDR  2013            0.0

[7028 rows x 4 columns]

In [8]:
columns_to_drop = [col for col in feature.columns if '분기' in col or '3년' in col or '5년' in col]
feature = feature.drop(columns=columns_to_drop)
feature

,Symbol,Name,결산월,회계년,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),현금및현금성자산구성비율(%),유형자산구성비율(%),...,자본금영업이익률(%),자본금세전계속사업이익률(%),자본금지배주주순이익률(%),총자산회전율(회),총부채회전율(회),총자본회전율(회),자본금회전율(회),부가가치(천원),자본생산성(%),노동생산성(천원)
0,A005930,삼성전자,12,2010,Annual,33.46,66.54,8.02,7.29,39.44,...,"1,851.90","2,153.58","1,760.31",1.25,3.68,1.90,172.29,NaN,NaN,NaN
1,A005930,삼성전자,12,2011,Annual,34.97,65.03,9.4,9.43,39.82,...,"1,743.07","1,915.50","1,491.08",1.14,3.32,1.73,183.84,NaN,NaN,NaN
2,A005930,삼성전자,12,2012,Annual,32.91,67.09,8.23,10.38,37.82,...,"3,236.64","3,333.10","2,583.29",1.19,3.53,1.81,224.07,NaN,NaN,NaN
3,A005930,삼성전자,12,2013,Annual,29.92,70.08,5.21,7.61,35.27,...,"4,098.54","4,274.50","3,322.65",1.16,3.70,1.68,254.81,NaN,NaN,NaN
4,A005930,삼성전자,12,2014,Annual,27.05,72.95,4.89,7.31,35.10,...,"2,788.27","3,105.80","2,571.83",0.93,3.26,1.30,229.75,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48225,A950070,중국고섬,12,2019,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48226,A950070,중국고섬,12,2020,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48227,A950070,중국고섬,12,2021,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48228,A950070,중국고섬,12,2022,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48229,A950070,중국고섬,12,2023,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
feature = feature.drop(columns=['부가가치(천원)', '자본생산성(%)', '노동생산성(천원)'])
feature

,Symbol,Name,결산월,회계년,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),현금및현금성자산구성비율(%),유형자산구성비율(%),...,ROE(당기순이익)(%),ROE(지배주주순이익)(%),"ROE(지배주주순이익,기말)(%)",자본금영업이익률(%),자본금세전계속사업이익률(%),자본금지배주주순이익률(%),총자산회전율(회),총부채회전율(회),총자본회전율(회),자본금회전율(회)
0,A005930,삼성전자,12,2010,Annual,33.46,66.54,8.02,7.29,39.44,...,19.89,20.37,18.46,"1,851.90","2,153.58","1,760.31",1.25,3.68,1.90,172.29
1,A005930,삼성전자,12,2011,Annual,34.97,65.03,9.4,9.43,39.82,...,14.43,14.65,13.78,"1,743.07","1,915.50","1,491.08",1.14,3.32,1.73,183.84
2,A005930,삼성전자,12,2012,Annual,32.91,67.09,8.23,10.38,37.82,...,21.41,21.65,19.80,"3,236.64","3,333.10","2,583.29",1.19,3.53,1.81,224.07
3,A005930,삼성전자,12,2013,Annual,29.92,70.08,5.21,7.61,35.27,...,22.45,22.80,20.65,"4,098.54","4,274.50","3,322.65",1.16,3.70,1.68,254.81
4,A005930,삼성전자,12,2014,Annual,27.05,72.95,4.89,7.31,35.10,...,14.71,15.06,14.23,"2,788.27","3,105.80","2,571.83",0.93,3.26,1.30,229.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48225,A950070,중국고섬,12,2019,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48226,A950070,중국고섬,12,2020,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48227,A950070,중국고섬,12,2021,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48228,A950070,중국고섬,12,2022,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48229,A950070,중국고섬,12,2023,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
label

       Symbol      Name   회계년  label_shifted
0     A038120     AD모터스  2011            0.0
1     A071660      SSCP  2011            0.0
2     A105070      금강제강  2011            0.0
3     A004550    대우송도개발  2011            0.0
4     A045260    디에이치패션  2011            0.0
...       ...       ...   ...            ...
7023  A900050    중국원양자원  2014            0.0
7024  A900050    중국원양자원  2015            0.0
7025  A900040   차이나그레이트  2017            0.0
7026  A950010  평산차업 KDR  2012            0.0
7027  A950010  평산차업 KDR  2013            0.0

[7028 rows x 4 columns]

In [15]:
df = pd.merge(label, feature, on=['Symbol', 'Name', '회계년'], how='left')
df

,Symbol,Name,회계년,label_shifted,결산월,주기,타인자본비율(%),자기자본비율(%),차입금의존도(%),현금및현금성자산구성비율(%),...,ROE(당기순이익)(%),ROE(지배주주순이익)(%),"ROE(지배주주순이익,기말)(%)",자본금영업이익률(%),자본금세전계속사업이익률(%),자본금지배주주순이익률(%),총자산회전율(회),총부채회전율(회),총자본회전율(회),자본금회전율(회)
0,A038120,AD모터스,2011,0.0,12,Annual,19.35,80.65,2.34,2.21,...,N/A(IFRS),N/A(IFRS),-85.43,N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS)
1,A071660,SSCP,2011,0.0,12,Annual,60.94,39.06,48.26,3.49,...,6.57,7.19,6.85,-2.33,-12.34,122.24,0.28,0.49,0.69,12.81
2,A105070,금강제강,2011,0.0,12,Annual,68.45,31.55,46.38,6.20,...,-16.87,-16.87,-18.38,-218.53,-397.80,-331.59,0.90,1.41,2.53,49.70
3,A004550,대우송도개발,2011,0.0,12,Annual,82.96,17.04,1.57,0.32,...,-46.87,-47.68,-37.90,-10.17,-9.59,-39.79,0.03,0.03,0.25,0.21
4,A045260,디에이치패션,2011,0.0,12,Annual,4.94,95.06,0.03,8.02,...,-28.38,-28.38,-25.59,-25.39,-44.19,-44.06,0.12,0.63,0.15,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7023,A900050,중국원양자원,2014,0.0,12,Annual,10.20,89.80,0.00,0.23,...,-19.96,-19.94,-20.91,-127.76,-121.96,-116.79,0.05,0.45,0.05,0.32
7024,A900050,중국원양자원,2015,0.0,12,Annual,29.58,70.42,1.60,0.01,...,-19.80,-19.84,-21.21,-10.41,-52.53,-50.33,0.22,1.06,0.27,0.69
7025,A900040,차이나그레이트,2017,0.0,12,Annual,14.31,85.69,4.21,43.52,...,-3.39,-3.39,-3.55,-136.85,-144.92,-118.60,0.89,5.31,1.07,37.24
7026,A950010,평산차업 KDR,2012,0.0,9,Annual,24.05,75.95,7.14,15.11,...,-13.60,-13.60,-14.80,-104.07,"-1,308.46","-1,310.17",0.29,1.24,0.38,37.02
7027,A950010,평산차업 KDR,2013,0.0,9,Annual,24.31,75.69,13.41,23.89,...,-0.24,-0.24,-0.16,12.40,-7.99,-9.95,0.18,0.73,0.24,9.70

In [16]:
df.to_csv('csv/feature/후보피처1.csv',encoding='utf-8-sig')

## 결측치

In [58]:
df = pd.read_csv('csv/feature/후보피처1_숫자.csv',index_col=0)
df.describe()

               회계년  label_shifted          결산월    타인자본비율(%)    차입금의존도(%)  현금및현금성자산구성비율(%)  유형자산구성비율(%)  무형자산구성비율(%)   차입부채/영업수익(%)  차입부채/영업이익(배)  차입부채/EBITDA(배)        유보율(%)   유보액/총자산(%)    *매출원가율(%)  *영업수익/영업비용(%)
count  7249.000000    7249.000000  7249.000000  7249.000000  7249.000000      7249.000000  7249.000000  7249.000000    7214.000000   1638.000000     3161.000000  6.494000e+03  6494.000000  7210.000000    7249.000000
mean   2017.269416       0.140709    11.913091    46.080654    26.965063         9.327129    24.375766     3.262566     260.597743     81.024414       32.286055  5.952197e+03    45.349058    80.544189      86.819070
std       3.347284       0.347745     0.827845    57.446545    34.259311        11.661061    19.980703     6.536255    4454.055776    742.245001      168.658581  1.591526e+05    23.994922    49.401463      22.449541
min    2011.000000       0.000000     3.000000     0.260000     0.000000         0.000000     0.000000     0.000000       0.000000      0.000000        0.000000  2.000000e-02     0.010000     0.000000       0.000000
25%    2014.000000       0.000000    12.000000    26.230000     9.840000         1.970000     6.750000     0.320000      17.912500      9.045000        4.270000  1.606150e+02    26.722500    71.137500      81.890000
50%    2018.000000       0.000000    12.000000    44.210000    25.520000         5.220000    20.810000     1.020000      46.020000     22.605000        9.740000  4.416300e+02    44.325000    86.865000      94.270000
75%    2020.000000       0.000000    12.000000    61.050000    38.920000        11.830000    37.960000     3.100000      95.260000     53.930000       21.340000  9.440250e+02    62.960000    94.795000      99.630000
max    2022.000000       1.000000    12.000000  4143.510000  2252.490000        90.170000    96.550000    81.440000  304685.380000  29022.150000     4798.190000  7.159649e+06   127.060000  3197.440000     309.820000

In [59]:
df.columns

Index(['Symbol', '회계년', 'label_shifted', 'Name', '레이블', '결산월', '주기',
       '타인자본비율(%)', '자기자본비율(%)', '차입금의존도(%)', '현금및현금성자산구성비율(%)', '유형자산구성비율(%)',
       '무형자산구성비율(%)', '부채비율(%)', '차입금비율(%)', '총자산/총자본(%)', '차입부채조달금리(평균)(%)',
       '차입부채조달금리(기말)(%)', '차입부채/영업수익(%)', '차입부채/영업이익(배)', '차입부채/EBITDA(배)',
       '현금흐름/총자산(%)', '현금흐름/총자본(%)', '현금흐름/총부채(%)', '현금흐름/총차입부채(%)',
       '현금흐름/영업수익(%)', '자기자본현금흐름률(%)', '자기자본현금흐름률(보통)(%)', '유보율(%)',
       '유보액/총자산(%)', '영업수익증가율(전년동기)(%)', '매출액증가율(전년동기)(%)', '매출원가증가율(전년동기)(%)',
       '매출총이익증가율(전년동기)(%)', '판매비와관리비증가율(전년동기)(%)', '영업이익증가율(전년동기)(%)',
       '*조정영업이익증가율(전년동기)(%)', '세전계속사업이익증가율(전년동기)(%)', '계속사업이익증가율(전년동기)(%)',
       '중단사업이익증가율(전년동기)(%)', '당기순이익증가율(전년동기)(%)', '총포괄이익증가율(전년동기)(%)',
       'EBITDA증가율(전년동기)(%)', '총자산증가율(전년동기)(%)', '유형자산증가율(전년동기)(%)',
       '무형자산증가율(전년동기)(%)', '총부채증가율(전년동기)(%)', '총차입부채증가율(전년동기)(%)',
       '총자본증가율(전년동기)(%)', '자본금증가율(전년동기)(%)', 'EPS증가율(전년동기)(%)',
       'EPS(계속사업)증가율(전년동기)(%)', 'EPS증가율(보통주,전년동기)(%)', 'BPS증가율(전년동기)(%)',
       'BPS증가율(무형자산차감,전년동기)(%)', 'CFPS증가율(전년동기)(%)', 'CFPS증가율(보통주,전년동기)(%)',
       'SPS증가율(전년동기)(%)', 'EBITDAPS증가율(전년동기)(%)', 'DPS증가율(보통주,전년동기)(%)',
       'DPS증가율(보통주,현금,전년동기)(%)', 'DPS증가율(무상조정전,보통주,현금,전년동기)(%)', '매출총이익률(%)',
       '영업이익률(%)', '*조정영업이익률(%)', 'EBITDA마진율(%)', '세전계속사업이익률(%)', '계속사업이익률(%)',
       '당기순이익률(%)', '총포괄이익률(%)', '지배주주순이익률(영업이익대비)(%)',
       '지배주주순이익률(세전계속사업이익대비)(%)', '*매출원가율(%)', '*판관비율(%)', '*영업수익/영업비용(%)',
       'ROA(영업이익)(%)', 'ROA(세전계속사업이익)(%)', 'ROA(당기순이익)(%)', 'ROA(총포괄이익)(%)',
       'ROE(영업이익)(%)', 'ROE(세전계속사업이익)(%)', 'ROE(당기순이익)(%)',
       'ROE(지배주주순이익,기말)(%)', '자본금영업이익률(%)', '자본금세전계속사업이익률(%)',
       '자본금지배주주순이익률(%)', '총자산회전율(회)', '총부채회전율(회)', '총자본회전율(회)', '자본금회전율(회)',
       '시장'],
      dtype='object')

In [20]:
# 한글값 null로 처리 (ex)완전잠식)
for i in df.columns :
    df[i] = pd.to_numeric(df[i], errors='coerce')

In [21]:
df.describe()

       Symbol  Name          회계년  label_shifted          결산월   주기    타인자본비율(%)    자기자본비율(%)    차입금의존도(%)  현금및현금성자산구성비율(%)  유형자산구성비율(%)  무형자산구성비율(%)      부채비율(%)     차입금비율(%)   총자산/총자본(%)  차입부채조달금리(평균)(%)  차입부채조달금리(기말)(%)  차입부채/영업수익(%)  차입부채/영업이익(배)  차입부채/EBITDA(배)  현금흐름/총자산(%)  현금흐름/총자본(%)  현금흐름/총부채(%)  현금흐름/총차입부채(%)  현금흐름/영업수익(%)  자기자본현금흐름률(%)  자기자본현금흐름률(보통)(%)       유보율(%)   유보액/총자산(%)  영업수익증가율(전년동기)(%)  매출액증가율(전년동기)(%)  매출원가증가율(전년동기)(%)  매출총이익증가율(전년동기)(%)  판매비와관리비증가율(전년동기)(%)  영업이익증가율(전년동기)(%)  *조정영업이익증가율(전년동기)(%)  세전계속사업이익증가율(전년동기)(%)  계속사업이익증가율(전년동기)(%)  중단사업이익증가율(전년동기)(%)  당기순이익증가율(전년동기)(%)  지배주주순이익증가율(전년동기)(%)  총포괄이익증가율(전년동기)(%)  지배주주총포괄이익증가율(전년동기)(%)  EBITDA증가율(전년동기)(%)  총자산증가율(전년동기)(%)  유형자산증가율(전년동기)(%)  무형자산증가율(전년동기)(%)  총부채증가율(전년동기)(%)  총차입부채증가율(전년동기)(%)  총자본증가율(전년동기)(%)  지배주주지분증가율(전년동기)(%)  자본금증가율(전년동기)(%)  EPS증가율(전년동기)(%)  EPS(계속사업)증가율(전년동기)(%)  EPS증가율(보통주,전년동기)(%)  BPS증가율(전년동기)(%)  BPS증가율(무형자산차감,전년동기)(%)  CFPS증가율(전년동기)(%)  CFPS증가율(보통주,전년동기)(%)  SPS증가율(전년동기)(%)  EBITDAPS증가율(전년동기)(%)  DPS증가율(보통주,전년동기)(%)  DPS증가율(보통주,현금,전년동기)(%)  DPS증가율(무상조정전,보통주,현금,전년동기)(%)    매출총이익률(%)     영업이익률(%)  *조정영업이익률(%)  EBITDA마진율(%)  세전계속사업이익률(%)   계속사업이익률(%)    당기순이익률(%)  지배주주순이익률(%)    총포괄이익률(%)  지배주주총포괄이익률(%)  지배주주순이익률(영업이익대비)(%)  지배주주순이익률(세전계속사업이익대비)(%)    *매출원가율(%)     *판관비율(%)  *영업수익/영업비용(%)  ROA(영업이익)(%)  ROA(세전계속사업이익)(%)  ROA(당기순이익)(%)  ROA(총포괄이익)(%)  ROE(영업이익)(%)  ROE(세전계속사업이익)(%)  ROE(당기순이익)(%)  ROE(지배주주순이익)(%)  ROE(지배주주순이익,기말)(%)  자본금영업이익률(%)  자본금세전계속사업이익률(%)  자본금지배주주순이익률(%)    총자산회전율(회)    총부채회전율(회)    총자본회전율(회)    자본금회전율(회)
count     0.0   0.0  7028.000000    7028.000000  7028.000000  0.0  7028.000000  6939.000000  7028.000000      7028.000000  7028.000000  7028.000000  6801.000000  6864.000000  6776.000000       6797.00000      6705.000000   6927.000000   1401.000000     3213.000000  7012.000000  6924.000000  7009.000000    6595.000000   6911.000000   6924.000000       6924.000000  4827.000000  6271.000000       6963.000000      6962.000000       6650.000000        5791.000000          7001.000000        462.000000           469.000000            448.000000          426.000000          454.000000         441.000000           462.000000         456.000000              476.00000         2272.000000      7009.000000       6933.000000       6673.000000      6980.000000        6474.000000      6830.000000         6834.000000      7001.000000       461.000000             425.000000           461.000000      6848.000000             6675.000000       1595.000000           1595.000000      6959.000000           2276.000000           859.000000              841.000000                    840.000000  7001.000000  6925.000000  6925.000000   6932.000000   6905.000000  6907.000000  6906.000000  6908.000000  6903.000000    6906.000000          1179.000000              1234.000000  6995.000000  6923.000000    7028.000000   7012.000000       7012.000000    7012.000000    7012.000000   6935.000000       6923.000000    6922.000000      6923.000000         6896.000000  6962.000000      6887.000000     6892.000000  7012.000000  7012.000000  6938.000000  7002.000000
mean      NaN   NaN  2017.268355       0.138589    11.914627  NaN    49.285371    52.248065    28.666116        10.783604    28.566393     5.049612   136.063483    86.235946   233.015733          7.06965         9.382340     71.862427     51.182691       22.878687    -7.367566   -18.093476   -20.975320     -31.792018    -28.202687    -18.262536        -18.265417   345.229113    40.529593          6.518048         6.489677          5.660911          14.255250            11.235461         52.056861            50.985096             52.707321           34.779906          -41.044119          42.540317            42.178355          42.159649               47.38563           12.220022         9.457325         13.092158         14.368283        20.863728          23.465281        10.455766            9.711375        14.600201        36.677939              28.754235            37.194751        -2.099855               -0.684682         19.800376             19.724890        -3.121451              7.069991            -4.932421               -6.198954                     -5.878143    19.626639   -24.437961   -24.470898    -17.497053    -35.210081   -35.090776   -36.588436   -35.619118   -35.608961     -34.829416           -39.284487                75.573671    80.363320    43.419143      87.624078     -6.317242        -10.533217     -11.024643     -10.792546    -15.311115        -26.215502     -27.451855       -27.608508          -31.185873   -60.841181       -92.126071      -90.899463     0.663982     1.724054     1.832028    12.246781
std       NaN   NaN     3.381907       0.345541     0.814761  NaN    29.784939    22.341224    21.252704        11.911325    20.626924     8.725208   144.273521   111.362750   135.504272         18.36248        35.607131     98.617178     88.894803       61.714296    19.630911    56.486475    71.057288     136.443122     99.204008     57.098735         57.097761   270.109759    23.233310         68.371499        68.448242         57.192140         113.287673            50.108613        196.790422           196.819438            223.826966          190.221774          189.336960         198.635048           205.579324         185.416706              202.55028          138.319720        54.803980         84.313054        118.863374        95.363836         115.347571        74.741849           74.316625        49.242842       197.986106             180.687862           198.917001        57.539608               64.836823        154.045364            154.258891        62.551077            136.066102            54.035794               52.096482                     61.518204    30.931387    75.942996    75.975449     77.883123     98.020201    97.406870   103.258846   102.010418   103.287990     102.862416           289.820042               154.033023    30.941273    78.577807      20.485461     10.311630         19.117720      19.851239      20.114975     39.008197         57.193681      58.933905        59.866064           76.096787   115.874889       162.813054      160.549492     0.485607     1.916618     2.861725    30.126203
min       NaN   NaN  2011.000000       0.000000     3.000000  NaN     1.030000     0.120000     0.000000         0.000000     0.000000     0.000000     1.040000     0.000000   101.040000        -26.22000        -4.130000      0.000000      0.000000        0.000000  -311.250000  -918.720000  -957.910000    -991.330000   -970.090000   -969.600000       -969.600000     0.020000     0.010000       -100.000000      -194.070000       -100.000000        -100.000000           -98.960000        -99.280000           -99.280000            -99.980000          -99.740000         -100.000000         -99.830000           -99.970000         -99.630000              -99.47000          -99.970000       -95.840000       -100.000000       -100.000000       -96.560000        -100.000000       -99.850000          -99.850000       -97.080000       -99.950000             -99.810000           -99.950000       -99.900000              -99.890000        -99.980000            -99.980000      -100.100000            -99.970000          -100.000000             -100.000000                   -100.000000  -802.730000  -980.960000  -980.960000   -990.700000   -994.400000  -998.290000  -998.290000  -998.290000  -994.380000    -984.850000          -997.610000              -985.870000     0.000000   -30.790000       0.000000   -119.320000       -316.540000    -318.880000    -318.550000   -868.560000       -986.150000    -992.880000      -992.880000         -976.140000  -978.720000      -991.230000     -991.540000     0.000000     0.000000     0.000000     0.000000
25%       NaN   NaN  2014.000000       0.000000    12.000000  NaN    30.987500    35.815000    12.420000         3.040000    10.530000     0.530000    43.430000    18.120000   143.220000          3.36000         3.240000     18.895000      9.410000        4.400000   -12.395000   -25.090000   -28.230000     -48.145000    -24.175000    -25.852500        -25.852500   108.670000    22.500000        -19.990000       -20.025000        -17.540000         -39.240000           -11.230000        -65.742500           -66.550000            -79.635000          -81.535000         -100.000000         -79.000000           -77.932500         -77.457500              -77.77250          -66.920000       -10.770000        -10.250000        -27.810000       -15.702500         -21.020000       -16.127500          -16.335000         0.000000       -80.350000             -83.190000           -80.350000       -20.860000              -21.760000        -67.275000            -67.495000       -28.665000            -68.882500           -33.330000              -33.330000                    -33.747500     5.930000   -18.380000   -18.480000    -12.090000    -31.150000   -30.955000   -32.422500   -31.262500   -32.050000     -30.967500          -169.000000                64.197500    71.220000    11.415000      83.742500     -9.002500        -15.510000     -16.170000     -16.182500    -19.210000        -32.730000     -34.070000       -33.965000          -34.460000   -85.065000      -132.755000     -132.265000     0.330000     0.730000     0.580000     2.040000
50%       NaN   NaN  2018.000000       0.000000    12.000000  NaN    49.050000    51.280000    28.440000         6.865000    26.515000     1.675000    92.810000    54.400000   192.165000          4.92000         4.880000     44.630000     23.640000        9.240000    -2.860000    -5.285000    -6.030000      -9.820000     -4.050000     -5.445000         -5.480000   284.020000    38.010000         -3.390000        -3.395000         -1.675000          -9.500000             3.000000        -18.865000           -21.900000            -38.810000          -41.505000         -100.000000         -33.840000           -37.075000         -34.810000              -32.83000          -28.695000        -0.950000         -1.750000         -6.460000         1.240000           0.000000        -3.455000           -3.650000         0.000000       -39.860000             -42.370000           -40.460000        -7.170000               -7.120000        -30.450000            -30.810000        -9.270000            -32.595000             0.000000                0.000000                      0.000000    13.740000    -5.350000    -5.350000     -0.790000     -9.450000    -9.270000    -9.595000    -9.220000    -9.250000      -8.850000            21.390000                85.290000    86.260000    22.220000      94.715000     -3.270000         -6.090000      -6.160000      -5.985000     -6.550000        -12.410000     -12.555000       -12.510000          -12.225000   -28.315000       -52.110000      -51.675000     0.580000     1.280000     1.170000     5.190000
75%       NaN   NaN  2020.000000       0.000000    12.000000  NaN    64.720000    69.210000    41.582500        14.160000    43.472500     5.435000   172.230000   110.080000   270.677500          7.57000         7.690000     84.755000     52.890000       18.690000     2.010000     3.902500     4.320000       7.420000      2.830000      4.110000          4.110000   543.755000    56.775000         13.740000        13.737500         15.330000          23.880000            21.720000         83.252500            82.750000             72.972500           76.075000         -100.000000          88.750000            81.037500          80.190000               85.30000           29.650000        11.760000         10.450000          9.360000        23.322500          25.600000        10.575000            9.952500        13.510000        73.980000              66.690000            73.980000         1.922500                2.450000         37.855000             37.540000         7.960000             24.855000             0.000000                0.000000                      0.000000    28.760000    -0.590000    -0.580000      3.842500     -1.650000    -1.680000    -1.680000    -1.530000    -1.330000      -1.240000           104.775000               100.950000    94.070000    45.995000      99.362500     -0.440000         -1.230000      -1.290000      -1.060000     -0.780000         -2.345000      -2.392500        -2.315000           -2.157500    -3.922500       -10.805000      -10.272500     0.890000     2.120000     2.120000    12.040000
max       NaN   NaN  2022.000000       1.000000    12.000000  NaN   790.980000    98.970000   459.080000        90.170000    96.550000    81.460000   998.730000   968.560000   995.020000        676.04000       975.110000    995.630000    965.450000      998.860000   168.950000   408.930000   540.240000     979.970000    908.730000    408.930000        408.930000   999.910000   136.580000        983.640000       983.640000        744.850000         996.290000           909.190000        983.300000           983.300000            985.110000          997.300000          979.600000         999.400000           999.370000         940.390000              991.28000          933.680000       827.230000        999.240000        999.870000       998.130000         987.530000       937.710000          937.710000       939.030000       992.720000             984.520000           992.720000       955.250000              959.270000        979.910000            979.910000       972.440000            997.250000           517.200000              517.200000                    900.000000   100.000000    62.300000    62.300000    725.750000    559.150000   898.070000   898.070000   898.070000   898.070000     898.070000           869.920000               992.530000   902.730000   984.760000     265.270000     95.500000        142.090000     167.950000     169.000000    221.490000        329.440000     343.450000       348.190000          785.680000   984.820000       964.400000      952.290000     8.170000    59.540000   103.060000   923.120000

In [23]:
a = pd.DataFrame()
a = df.describe()
a.to_csv('csv/feature/결측치처리전_describe.csv', encoding='utf-8-sig')